---
version: 2
updates:
  # NOTE: Python and GitHub Actions dependencies are now managed by Renovate
  # See renovate.json for configuration
  # Dependabot is disabled for these to avoid conflicts

  # Maintain dependencies for Docker (if Docker is used)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(deps): "
    labels:
      - dependencies
      - docker
    open-pull-requests-limit: 10
    assignees:
      - "tuxpeople"

  # Maintain dependencies for Ruby (if Gemfile exists)
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    commit-message:
      prefix: "feat(deps): "
    labels:
      - dependencies
      - ruby
    open-pull-requests-limit: 10
    assignees:
      - "tuxpeople"

# Python and GitHub Actions are managed by Renovate (see renovate.json)
# - pip: Disabled (Renovate has better auto-merge rules)
# - github-actions: Disabled (Renovate handles this)
