---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: aadl.softwareupdate
    version: master
  - name: morgangraphics.nvm
    version: master

collections:
  - name: geerlingguy.mac
    version: 4.0.1
