---
- name: Initialize chezmoi from dotfiles repo
  ansible.builtin.command:
    cmd: chezmoi init https://github.com/tuxpeople/dotfiles.git
    creates: "{{ myhomedir }}/.config/chezmoi/chezmoi.toml"
  become: false

- name: Apply dotfiles via chezmoi
  ansible.builtin.command:
    cmd: chezmoi apply --no-pager
  become: false
  changed_when: false
