---
- name: Initialize/update chezmoi from dotfiles repo
  ansible.builtin.command:
    cmd: chezmoi init https://github.com/tuxpeople/dotfiles.git
  become: false
  changed_when: false

- name: Apply dotfiles via chezmoi
  ansible.builtin.command:
    cmd: chezmoi apply --no-pager --force
  become: false
  changed_when: false
