---
# tasks file for brew cu
- name: Test for installed brew
  ansible.builtin.shell: "command -v {{ mybrewbindir }}/brew"
  register: brew_exists
  become: no

- name: Test for installed brew plugin cu
  ansible.builtin.shell: "{{ mybrewbindir }}/brew cu -h"
  register: brewcu_exists
  become: no

- name: Ensure auto_upgrade casks are upgraded
  # Alternative: brew outdated --greedy --verbose | grep -v '(latest)' | awk '{print $1}' | xargs brew reinstall
  ansible.builtin.shell: "{{ mybrewbindir }}/brew cu -a -y"
  become: no
  environment:
    SUDO_ASKPASS: "{{ ansible_become_pass }}"