- name: Ensure .ssh folder exists
  file:
    path: "{{myhomedir}}/.ssh"
    state: directory
    mode: '0600'
  become: false

- name: Touch ssh-config, but do not change times this makes the task idempotent
  ansible.builtin.file:
    path: "{{myhomedir}}/.ssh/config"
    state: touch
    mode: '0600'
    modification_time: preserve
    access_time: preserve
  become: false

- name: Regenerating ssh config
  ansible.builtin.shell: "truncate -s0 {{myhomedir}}/.ssh/config; for i in {{ ssh_config_src }}/*; do cat $i >> {{myhomedir}}/.ssh/config; echo '' >> {{myhomedir}}/.ssh/config; done; chmod 700 {{myhomedir}}/.ssh/config"
  become: false

- name: Update SSH Keys
  ansible.builtin.copy:
    src: "{{ssh_keys_src}}/"
    dest: "{{myhomedir}}/.ssh/"
    remote_src: "true"
  become: false

- name: Compiling list of SSH private keys
  ansible.builtin.shell: "ls {{myhomedir}}/.ssh/id* | grep -v pub"
  register: installed_ssh_private_keys
  changed_when: "installed_ssh_private_keys.rc != 0"
  become: false

- name: Fix permissions of SSH private keys
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: staff
    mode: '0600'
  with_items: "{{ installed_ssh_private_keys.stdout_lines }}"

- name: Compiling list of SSH public keys
  ansible.builtin.shell: "ls {{myhomedir}}/.ssh/id*pub"
  register: installed_ssh_public_keys
  changed_when: "installed_ssh_public_keys.rc != 0"
  become: false

- name: Fix permissions of SSH public keys
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: staff
    mode: '0644'
  with_items: "{{ installed_ssh_public_keys.stdout_lines }}"
