tap "buo/cask-upgrade"
tap "carvel-dev/carvel"
tap "devopyio/yamlfmt"
tap "emqx/mqttx"
tap "fluxcd/tap"
tap "gabrie30/utils"
tap "go-task/tap"
tap "hashicorp/tap"
tap "johanhaleby/kubetail"
tap "mfuentesg/tap"
tap "norwoodj/tap"
tap "nrlquaker/createzap"
tap "siderolabs/tap"
tap "tuxpeople/personal"
tap "utkuozdemir/pv-migrate"
tap "vmware-tanzu/tanzu"
# Simple, modern, secure file encryption
brew "age"
# Utility to check whether MAC addresses are already taken on a LAN
brew "arping"
# MPEG-4 command-line tool
brew "atomicparsley"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Encode and decode base64 files
brew "base64"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.2+
brew "bash-completion@2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross platform file encryption utility using blowfish
brew "bcrypt"
# CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
brew "cilium-cli"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Home for the Cluster Management API work, a subproject of sig-cluster-lifecycle
brew "clusterctl"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Container Signing
brew "cosign"
# Tool for interacting with remote images and registries
brew "crane"
# Cluster ssh tool for Terminal.app
brew "csshx"
# Validate and define text-based and dynamic configuration
brew "cue"
# Tool for downloading RTMP streaming media
brew "rtmpdump"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Load/unload environment variables based on $PWD
brew "direnv"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Utilities for the ext2, ext3, and ext4 file systems
brew "e2fsprogs"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Multi-format archive and compression library
brew "libarchive"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Scriptable ping program for checking if multiple hosts are up
brew "fping"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Highly caffeinated git GUI
brew "git-cola"
# Extensions to follow Vincent Driessen's branching model
brew "git-flow"
# Audit git repos for secrets
brew "gitleaks"
# Convert text strings to printed bars
brew "gnu-barcode"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# Library for USB device access
brew "libusb"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Command-driven, interactive function plotting
brew "gnuplot"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Task is a task runner/build tool that aims to be simpler and easier to use
brew "go-task"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# GUI for rsync
brew "grsync"
# Popular GNU data compression program
brew "gzip"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# CLI client for haste-server
brew "haste-client"
# Kubernetes package manager
brew "helm"
# Deploy Kubernetes Helm Charts
brew "helmfile"
# Improved top (interactive process viewer)
brew "htop"
# Tool for measuring webserver performance
brew "httperf"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Website copier/offline browser
brew "httrack"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Migrate or backup IMAP mail accounts
brew "imapsync"
# Calculate various network masks, etc. from a given IP address
brew "ipcalc"
# Tool to measure maximum TCP and UDP bandwidth
brew "iperf"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Command-line JSON pretty-printer
brew "jsonpp"
# Little helper to run CNCF's k3s in Docker
brew "k3d"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# User-friendly front-end to ssh-agent(1)
brew "keychain"
# Run local Kubernetes cluster in Docker
brew "kind"
# Tool to move from `docker-compose` to Kubernetes
brew "kompose"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Package manager for kubectl plugins
brew "krew"
# Static analysis tool for Kubernetes YAML files and Helm charts
brew "kube-linter"
# FAST Kubernetes manifests validator, with support for Custom Resources!
brew "kubeconform"
# Easily check your clusters for use of deprecated APIs
brew "kubent"
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Simple terminal UI for git commands
brew "lazygit"
# Manipulate OpenType and multiple-master fonts
brew "lcdf-typetools"
# Layer Four Traceroute (LFT), an advanced traceroute tool
brew "lft"
# Sophisticated file transfer program
brew "lftp"
# Linux virtual machines
brew "lima"
# Lynx-like WWW browser that supports tables, menus, etc.
brew "links"
# Rainbows and unicorns in your console!
brew "lolcat"
# Utility to list open files
brew "lsof"
# Text-based web browser
brew "lynx"
# Swiss Army Knife for macOS
brew "m-cli"
# CLI for Node.js style checker and lint tool for Markdown files
brew "markdownlint-cli"
# Mac App Store command-line interface
brew "mas"
# Utility for testing the memory subsystem
brew "memtester"
# Replacement for ls, cp and other commands for object storage
brew "minio-mc"
# Move, copy, append, and link multiple files
brew "mmv"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Remote terminal application
brew "mosh"
# Tools for manipulating MSDOS files
brew "mtools"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Tail multiple files in one terminal simultaneously
brew "multitail"
# CLI for MySQL with auto-completion and syntax highlighting
brew "mycli"
# MySQL logical backup tool
brew "mydumper"
# NCurses Disk Usage
brew "ncdu"
# FTP client with an advanced user interface
brew "ncftp"
# Utility for managing network connections
brew "netcat"
# Network grep
brew "ngrep"
# Port scanning utility for large networks
brew "nmap"
# Node.js JavaScript runtime and npm package manager
brew "node"
# Prometheus exporter for machine metrics
brew "node_exporter", restart_service: :changed
# Network performance measurement tool
brew "nuttcp"
# Oracle Cloud Infrastructure CLI
brew "oci-cli"
# OpenShift command-line interface tools
brew "openshift-cli"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Efficient rsh-like utility, for using hosts in parallel
brew "pdsh"
# Display the PID number for a given process name
brew "pidof"
# New zlib (gzip, deflate) compatible compressor
brew "zopfli"
# Parallel gzip
brew "pigz"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Tool for managing OCI containers and pods
brew "podman"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Show ps output as a tree
brew "pstree"
# Monitor data's progress through a pipe
brew "pv"
# Password generator
brew "pwgen"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Tools for and transforming and inspecting PDF files
brew "qpdf"
# Encoder and decoder for quoted-printable encoding
brew "qprint"
# QR Code generation
brew "qrencode"
# Rsync for cloud storage
brew "rclone"
# Reverse differential backup tool, over a network or locally
brew "rdiff-backup"
# Docker and OCI Registry Client in Go and tooling using those libraries
brew "regclient"
# Rename multiple files in a directory
brew "ren"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Fast, efficient and secure backup program
brew "restic"
# File system snapshot utility (based on rsync)
brew "rsnapshot"
# Utility that provides fast incremental file transfer
brew "rsync"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Terminal multiplexer with VT100/ANSI terminal emulation
brew "screen"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Advanced console-based IP subnet calculator
brew "sipcalc"
# Editor of encrypted files
brew "sops"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Add a public key to a remote machine's authorized_keys file
brew "ssh-copy-id", link: true
# SSLv3/TLS network protocol analyzer
brew "ssldump"
# Test SSL/TLS enabled services to discover supported cipher suites
brew "sslscan"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# System-level exploration and troubleshooting tool
brew "sysdig"
# Configuration helper for talos clusters
brew "talhelper"
# Command-line packet analyzer
brew "tcpdump"
# TCP/IP packet demultiplexer
brew "tcpflow"
# TCP connect to the given IP/port combo
brew "tcping"
# Active TCP connections monitoring tool
brew "tcpstat"
# Analyze tcpdump output
brew "tcptrace"
# Traceroute implementation using TCP packets
brew "tcptraceroute"
# User interface to the TELNET protocol
brew "telnet"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Terraform version manager inspired by rbenv
brew "tfenv"
# Linter for Terraform files
brew "tflint"
# Static analysis security scanner for your terraform code
brew "tfsec"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vulnerability scanner for container images, file systems, and Git repos
brew "trivy"
# RTF to other formats converter
brew "unrtf"
# Extraction utility for .zip compressed archives
brew "unzip"
# Creates fully functional virtual k8s cluster inside host k8s cluster's namespace
brew "vcluster"
# Disaster recovery for Kubernetes resources and persistent volumes
brew "velero"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Lookup tool for domain names and other internet resources
brew "whois"
# Show the current WiFi network password
brew "wifi-password"
# Tiny, wget-like FTP client for uploading files
brew "wput"
# Linter for YAML files
brew "yamllint"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Imgpkg
brew "carvel-dev/carvel/imgpkg"
# Formats yaml files.
brew "devopyio/yamlfmt/yamlfmt"
# Flux CLI
brew "fluxcd/tap/flux"
# Quickly clone an entire org/users repositories into one directory
brew "gabrie30/utils/ghorg"
# Packer
brew "hashicorp/tap/packer"
# Vault
brew "hashicorp/tap/vault"
# Tail logs from multiple Kubernetes pods at the same time
brew "johanhaleby/kubetail/kubetail"
# ksd` is a tool, whose aim is help you to visualize in text plain your kubernetes secrets, either `yaml` or `json` outputs.
brew "mfuentesg/tap/ksd"
# Automatically generate markdown documentation for helm charts
brew "norwoodj/tap/helm-docs"
# CLI for out-of-band management of Kubernetes nodes created by Talos
brew "siderolabs/tap/talosctl"
# Persistent volume migration plugin for Kubernetes
brew "utkuozdemir/pv-migrate/pv-migrate"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# Apple TV Aerial screensaver
cask "aerial"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Text, code, and markup editor
cask "bbedit"
# Universal database tool and SQL client
cask "dbeaver-community"
# Drivers for DisplayLink docks, adapters and monitors
cask "displaylink"
# Enables DisplayLink screens prior to login
cask "displaylink-login-extension"
# Online diagram software
cask "drawio"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Finds duplicate files in a computer system
cask "dupeguru"
# Web browser
cask "firefox"
cask "font-roboto"
cask "font-roboto-mono"
# Free VPN client for FortiClient
cask "forticlient-vpn"
# Web browser
cask "google-chrome"
# Tools to protect your emails and files
cask "gpg-suite"
# Open-source video transcoder
cask "handbrake"
# Automated organisation
cask "hazel"
# IDE for Java development - community edition
cask "intellij-idea-ce"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Note taking and to-do application with synchronisation capabilities
cask "joplin"
# Personal data manager focusing on security
cask "keepassx"
# Host-based application firewall
cask "little-snitch"
# Software for Logitech devices
cask "logi-options+"
# Privacy-first, open-source platform for knowledge sharing and management
cask "logseq"
# Open-source, KeePass-client and password manager
cask "macpass"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Orchestrates virtual Ubuntu instances
cask "multipass"
cask "mysides"
# Rename a list of files quickly
cask "namechanger"
# WiFi site survey software and WiFi scanner
cask "netspot"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Create, run, and share large language models (LLMs)
cask "ollama-app"
# Virtual machine client
cask "omnissa-horizon-client"
# Tool to create native applications from command-line scripts
cask "platypus"
# Podcast platform
cask "pocket-casts"
# Browse, manage, inspect containers and images
cask "podman-desktop"
# IDE for Python programming - Community Edition
cask "pycharm-ce"
# Free and Open Source messaging and emailing app
cask "rambox"
# Archive manager for data compression and backups
cask "rar"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Remote management solution
cask "royal-tsx"
# Tool for sending personal documents to Kindles from Macs
cask "send-to-kindle"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Native GUI tool for relational databases
cask "tableplus"
# Mesh VPN based on WireGuard
cask "tailscale"
# Remote access and connectivity software focused on security
cask "teamviewer"
# Free and open-source OpenVPN client
cask "tunnelblick"
# Die Deutschschweizer Basisschrift ist eine didaktische Schrift, die für den Handschrifterwerb konzipiert worden ist. Sie ist bewusst keine Satzschrift, die gestalterische Möglichkeiten bei der Erstellung von Arbeitsblättern und Materialien zulässt. Es gibt daher auch keine fette oder kursive Version der Schrift. Das Konzept der Deutschschweizer Basisschrift setzt bewusst auf handschrifltiche Vorlagen von Lehrpersonen.
cask "tuxpeople-font-dch-basisschrift"
# Tool to install Linux/BSD distributions to a partition or USB drive
cask "unetbootin"
# Development environment
cask "vagrant"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Video communication and virtual meeting platform
cask "webex-meetings"
# Network protocol analyzer
cask "wireshark"
# Application for configuring any YubiKey
cask "yubico-yubikey-manager"
mas "1Password for Safari", id: 1569813296
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Affinity Publisher", id: 881418622
mas "Agenda", id: 1287445660
mas "Apple Configurator", id: 1037126344
mas "Bear", id: 1091189122
mas "DaisyDisk", id: 411643860
mas "ForkLift", id: 412448059
mas "FruitJuice", id: 671736912
mas "Goodnotes", id: 1444383602
mas "Grammarly for Safari", id: 1462114288
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Kubeterm", id: 6450548861
mas "LanScan", id: 472226235
mas "Lightweight PDF", id: 1450640351
mas "Magnet", id: 441258766
mas "Matter", id: 1548677272
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PDFCombo", id: 1030461463
mas "PDFScanner", id: 410968114
mas "Reeder", id: 1529448980
mas "Sid Meier's Railroads!", id: 536502825
mas "SQLPro for SQLite", id: 586001240
mas "Swift Playground", id: 1496833156
mas "Termius", id: 1176074088
mas "TextSniper", id: 1528890965
mas "Todoist", id: 585829637
mas "Toggl Track", id: 1291898086
mas "Unibox", id: 702816521
mas "VMware Remote Console", id: 1230249825
mas "Windows App", id: 1295203466
mas "WireGuard", id: 1451685025
vscode "4ops.terraform"
vscode "albert.tabout"
vscode "britesnow.vscode-toggle-quotes"
vscode "codezombiech.gitignore"
vscode "continue.continue"
vscode "davidanson.vscode-markdownlint"
vscode "dhoeric.ansible-vault"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "exiasr.hadolint"
vscode "fcrespo82.markdown-table-formatter"
vscode "foxundermoon.shell-format"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "gitlab.gitlab-workflow"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "irarainey.applicationregistrations"
vscode "joaompinto.vscode-graphviz"
vscode "kennylong.kubernetes-yaml-formatter"
vscode "lunuan.kubernetes-templates"
vscode "mgtrrz.terraform-completer"
vscode "misodee.vscode-nbt"
vscode "mitchdenny.ecdc"
vscode "mohamedfaizal.tf-az-codesnippet"
vscode "mohsen1.prettify-json"
vscode "ms-azure-load-testing.microsoft-testing"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-azure-github-copilot"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-azureterraform"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "oderwat.indent-rainbow"
vscode "pjmiravalle.terraform-advanced-syntax-highlighting"
vscode "platformio.platformio-ide"
vscode "psykosoldi3r.vscode-git-flow"
vscode "rabinhansda.flask-builder"
vscode "redhat.ansible"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "run-at-scale.terraform-doc-snippets"
vscode "samuelcolvin.jinjahtml"
vscode "signageos.signageos-vscode-sops"
vscode "tfsec.tfsec"
vscode "usernamehw.errorlens"
vscode "vscode-icons-team.vscode-icons"
vscode "will-stone.in-any-case"
vscode "yzdann.k8s-snippets"
vscode "yzhang.markdown-all-in-one"
