---
# https://dev.to/0xdonut/why-and-how-you-should-to-migrate-from-visual-studio-code-to-vscodium-j7d
- name: Remove extended attributes from Visual Studio Code.app
  ansible.builtin.shell: xattr -c "/Applications/Visual Studio Code.app"
  changed_when: false
  ignore_errors: true
  become: true
# settings.json is managed by chezmoi (tuxpeople/dotfiles)
