---
- hosts: all
  environment:
    PATH: "{{env_path}}"

  vars:
    - homebrew_use_brewfile: true

  pre_tasks:
    - import_tasks: ../tasks/pre/additional-facts.yml
    - import_tasks: ../tasks/pre/baseconfig.yml
    - import_tasks: ../tasks/pre/install-rosetta2.yml
    - import_tasks: ../tasks/pre/cleanup-deprecated-taps.yml
    - import_tasks: ../tasks/pre/cleanup-old-python-versions.yml
    - import_tasks: ../roles/ansible-mac-update/tasks/ssh.yaml

    - name: Ensure /private/etc/sudoers.d exists
      file:
        path: '/private/etc/sudoers.d'
        state: directory
      become: true

  tasks:
    - name: Main playbook execution with guaranteed sudo cleanup
      block:
        - name: Add temporary passwordless sudo permissions
          ansible.builtin.copy:
            content: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
            dest: "/private/etc/sudoers.d/99_tmp_ansible"
            validate: /usr/sbin/visudo -csf %s
            mode: 0440
          become: true

        - name: Install command line tools
          include_role:
            name: elliotweiser.osx-command-line-tools

        - name: Install Homebrew packages
          include_role:
            name: geerlingguy.mac.homebrew
          tags: ['homebrew']

        - name: Configure dotfiles
          include_role:
            name: geerlingguy.dotfiles
          when: configure_dotfiles
          tags: ['dotfiles']

        # - name: Install Mac App Store apps
        #   include_role:
        #     name: geerlingguy.mac.mas
        #   when: mas_installed_apps or mas_installed_app_ids
        #   tags: ['mas']

        - name: Configure Dock
          include_role:
            name: geerlingguy.mac.dock
          when: configure_dock
          tags: ['dock']

        - import_tasks: ../tasks/sudoers.yml
          when: configure_sudoers
          tags: ['sudoers']

        - import_tasks: ../tasks/terminal.yml
          when: configure_terminal
          tags: ['terminal']

        - import_tasks: ../tasks/osx.yml
          when: configure_osx
          tags: ['osx']

        - import_tasks: ../tasks/fonts.yml
          when: configure_osx
          tags: ['fonts']

        - import_tasks: ../tasks/extra-packages.yml
          tags: ['extra-packages']

        - import_tasks: ../tasks/sublime-text.yml
          when: configure_sublime
          tags: ['sublime-text']

        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
          tags: ['post']

      rescue:
        - name: Log playbook failure
          debug:
            msg: "⚠️  Playbook failed, but ensuring sudo cleanup runs"

      always:
        - name: Remove temporary passwordless sudo permissions (GUARANTEED)
          ansible.builtin.file:
            path: "/private/etc/sudoers.d/99_tmp_ansible"
            state: absent
          become: true
          ignore_errors: true
