---
- hosts: all
  gather_facts: false
  environment:
    PATH: "{{env_path}}"

  vars:
    homebrew_use_brewfile: true

  pre_tasks:
    - name: Load sudo password from 1Password
      ansible.builtin.set_fact:
        ansible_become_pass: "{{ lookup('community.general.onepassword', onepassword_sudo_item, errors='warn') }}"
      when:
        - ansible_become_pass is not defined or ansible_become_pass | length == 0
        - onepassword_sudo_item is defined
      become: false
      tags: always

    - name: Ensure /private/etc/sudoers.d exists
      file:
        path: '/private/etc/sudoers.d'
        state: directory
      become: true
      tags: always

    - name: Add temporary passwordless sudo permissions
      ansible.builtin.copy:
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: "/private/etc/sudoers.d/99_tmp_ansible"
        validate: /usr/sbin/visudo -csf %s
        mode: 0440
      become: true
      tags: always

    - name: Gather system facts
      ansible.builtin.setup:
      become: true
      tags: always

    - import_tasks: ../tasks/pre/additional-facts.yml
      tags: always
    - import_tasks: ../tasks/pre/baseconfig.yml

    - name: Validate required variables are defined
      ansible.builtin.assert:
        that:
          - env_path is defined
          - env_path | length > 0
          - mybrewbindir is defined
          - myhomedir is defined
        fail_msg: "Required variables missing. Check group_vars/macs/general.yml and additional-facts.yml"
        success_msg: "All required variables validated successfully"

    - import_tasks: ../tasks/pre/install-rosetta2.yml
    - import_tasks: ../tasks/pre/cleanup-deprecated-taps.yml
    - import_tasks: ../tasks/pre/cleanup-old-python-versions.yml
    - import_tasks: ../tasks/pre/ssh.yml

    - name: Ensure ~/bin directory exists
      ansible.builtin.file:
        path: "{{ myhomedir }}/bin"
        state: directory
        mode: '0755'
      become: false

    - name: Deploy vault password script from template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../files/scripts/vault_password_from_1password.sh.j2"
        dest: "{{ myhomedir }}/bin/vault_password_mac_dev_playbook"
        mode: '0700'
      become: false

    - name: Load GitHub token from 1Password (batch with other 1Password prompts)
      ansible.builtin.shell: op read "{{ onepassword_github_token_ref }}"
      register: github_token_result
      no_log: true
      become: false
      when: onepassword_github_token_ref is defined

    - name: Set GitHub token fact
      ansible.builtin.set_fact:
        github_personal_token: "{{ github_token_result.stdout }}"
      no_log: true
      when: github_token_result is defined and not github_token_result.failed

  tasks:
    - name: Main playbook execution with guaranteed sudo cleanup
      block:

        - name: Install command line tools
          include_role:
            name: elliotweiser.osx-command-line-tools

        - name: Install Homebrew packages
          include_role:
            name: geerlingguy.mac.homebrew
          tags: ['homebrew']

        - name: Ensure .config directory exists for dotfile symlinks
          ansible.builtin.file:
            path: "{{ myhomedir }}/.config"
            state: directory
            mode: '0755'
          become: false
          when: configure_dotfiles
          tags: ['dotfiles']

        - import_tasks: ../tasks/dotfiles.yml
          when: configure_dotfiles
          tags: ['dotfiles']

        # Mac App Store (MAS) integration - DISABLED
        # Why: All Mac App Store apps are managed via Homebrew casks in Brewfiles instead
        # Brewfiles location: files/brewfile/business_mac/Brewfile and private_mac/Brewfile
        # Benefits: Single package manager (Homebrew), no mas CLI authentication issues
        # Alternative: If you need mas, configure mas_installed_apps in group_vars and uncomment block below
        # To re-enable:
        #   1. Install mas CLI: brew install mas
        #   2. Login to App Store: mas signin email@example.com (may have auth issues)
        #   3. Uncomment block below
        #   4. Test on non-production Mac first
        # See: https://github.com/mas-cli/mas#known-issues
        #
        # - name: Install Mac App Store apps
        #   include_role:
        #     name: geerlingguy.mac.mas
        #   when: mas_installed_apps or mas_installed_app_ids
        #   tags: ['mas']

        # Dock configuration via tasks/post/various-settings.yml (with dock tag)
        # Note: geerlingguy.mac.dock role disabled in favor of direct dockutil commands

        - import_tasks: ../tasks/osx.yml
          when: configure_osx
          tags: ['osx']

        - import_tasks: ../tasks/fonts.yml
          when: configure_osx
          tags: ['fonts']

        - import_tasks: ../tasks/extra-packages.yml
          tags: ['extra-packages']

        - import_tasks: ../tasks/dock.yml
          tags: ['dock']

        - import_tasks: ../tasks/post/various-settings.yml
          tags: ['post']

        - name: Run configured post-provision ansible task files
          include_tasks:
            file: "{{ item }}"
            apply:
              tags: ['post']
          loop: "{{ post_provision_tasks | default([]) }}"
          tags: ['post']

      rescue:
        - name: Log playbook failure
          debug:
            msg: "⚠️  Playbook failed, but ensuring sudo cleanup runs"

      always:
        - name: Remove temporary passwordless sudo permissions (GUARANTEED)
          ansible.builtin.file:
            path: "/private/etc/sudoers.d/99_tmp_ansible"
            state: absent
          become: true
          ignore_errors: true
          tags: always
