- name: "Detect who am I"
  ansible.builtin.command: "whoami"
  register: whoami
  changed_when: whoami.rc != 0

- name: "Set fact ansible_user to {{ whoami.stdout }}"
  set_fact:
    ansible_user: "{{ whoami.stdout }}"

- name: Check if this is a MacBook
  block:
    # https://apple.stackexchange.com/a/98089
    - name: "Get model information"
      ansible.builtin.shell: "curl https://support-sp.apple.com/sp/product?cc=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}' | cut -c 9-)"
      register: SPHardwareDataType
      changed_when: SPHardwareDataType.rc != 0

    - name: "Set fact macbook if appropriate"
      set_fact:
        macbook: true
      when: "'MacBook' in SPHardwareDataType.stdout"

- name: Check if this is a business or a private device
  block:
    - name: "Set fact myenv to business"
      set_fact:
        myenv: "business"
      when: myhostname is match("ws.*")

    - name: "Set fact myenv to private"
      set_fact:
        myenv: "private"
      when: not myhostname is match("ws.*")

- name: Set homedir
  block:
    - name: Getting Users Homedir
      user:
        name: "{{ ansible_user }}"
        state: present
      register: this_user_registered

    - name: "Set fact myhomedir to {{ this_user_registered.home }}"
      set_fact:
        myhomedir: "{{ this_user_registered.home }}"

- name: "Set fact mybrewbindir to {{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/bin"
  set_fact:
    mybrewbindir: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/bin"