- name: "Set hostname"
  ansible.builtin.hostname:
    name: "{{ myhostname }}"

- name: "Set timezone"
  community.general.timezone:
    name: "{{ timezone }}"

- name: Configure NTP
  shell: "{{ item }}"
  with_items:
    - '/usr/sbin/systemsetup -setnetworktimeserver "{{ ntpserver }}"'
    - '/usr/sbin/systemsetup -setusingnetworktime on'

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
#osascript -e 'tell application "System Preferences" to quit'